# Site settings
title: Nabil Hachicha
email: nabil.hachicha@gmail.com
description: I'm Nabil Hachicha, an Android software engineer in London. I work at <a href="http://www.theappbusiness.com" target="tab">TheAppBusiness</a>.
baseurl: ""
url: "http://nabilhachicha.com"

# Build settings
markdown: kramdown
permalink: pretty
